# Extend the base_actor config
defaults:
  - base_actor

name: act

action_horizon: 1
pred_horizon: 8
obs_horizon: 1
predict_past_actions: ${predict_past_actions}

optimization:
  loss_fn: L1Loss
  optimizer: adam
  beta_kl: 10

inference:
  temporal_ensemble_m: 0.01



ConditionalVAE:
  dim_state: 58
  dim_latent: 16
  dim_action: 10
  action_chunk_size: ${pred_horizon}

  TransformerEncoder:
    num_layers: 4
    layer_norm: True

    TransformerEncoderLayer:
      dim_model: 256
      num_heads: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: relu
      normalize_before: False

  ActionTransformer:
    dim_model: 512  # Parent parameters such as 'dim_model' automatically propagate to and are shared by children of 'ActionTransformer' unless overriden.

    TransformerEncoder:
      num_layers: 6
      layer_norm: True
      TransformerEncoderLayer:
        num_heads: 8
        dim_feedforward: 2048
        dropout: 0.1
        activation: relu
        normalize_before: False

    TransformerDecoder:
      num_layers: 6
      TransformerDecoderLayer:
        num_heads: 8
        dim_feedforward: 2048
        dropout: 0.1
        activation: relu
        normalize_before: False









