# Extend the base_actor config
defaults:
  - base_actor

name: act

action_horizon: 1
pred_horizon: 32
obs_horizon: 1
predict_past_actions: ${predict_past_actions}

optimization:
  loss_fn: L1Loss
  optimizer: adam
  beta_kl: 1.0

inference:
  temporal_ensemble_m: 0.01



ConditionalVAE:
  dim_state: 10
  dim_latent: 16
  dim_action: 58

  TransformerEncoder:
    num_layers: 4
    layer_norm: True

    TransformerEncoderLayer:
      dim_model: 256
      num_heads: 8
      dim_feedforward: 2048
      dropout: 0.1
      activation: relu
      normalize_before: False

  ActionTransformer:
    num_heads: 8
    num_encoder_layers: 6
    num_decoder_layers: 6

    TransformerEncoder:
      dim_model: 512
      dim_feedforward: 2048
      dropout: 0.1
      activation: relu
      normalize_before: False

    TransformerDecoder:
      dim_model: 512
      num_decoder_layers: 6
      dim_feedforward: 2048
      dropout: 0.1
      activation: relu
      normalize_before: False









